### ISSUE TITLE
Admin Page Login Logic_view

### ISSUE THREAD

**Issue by Lambu-here** [Procom-24/Attendance_Management_System_Procom24#14]
#12 : File: Attendance_management_System_Procom24/registration/views.py => login_view

The custom UserAccount model created to be used for authenticating isnt able to authenticate using built-in authentication methods in Django.

However, hardcoded values work fine within the view.

@Ashad001 
@owais-siddiqi 
@samaha-rizvi-4578

**Comment by samaha-rizvi-4578** [comment]
The issue has been resolved. It is taking values from the userAccount model.

**Comment by samaha-rizvi-4578** [comment]
fixed
